#!/usr/bin/env python3
"""Prints src/JsonBeef/JsonIdentifierTables.bf: the non-ASCII code point ranges of JSON5's identifier
characters (ECMAScript 5.1 §7.6, which JSON5 1.0.0 §3 uses for unquoted member names), from Python's
unicodedata (its Unicode version is named in the output):

  IdentifierStart: UnicodeLetter (Lu, Ll, Lt, Lm, Lo, Nl)
  IdentifierPart:  IdentifierStart and UnicodeCombiningMark (Mn, Mc), UnicodeDigit (Nd),
                   UnicodeConnectorPunctuation (Pc); ZWNJ and ZWJ are added by the reader

(`$`, `_`, the ASCII letters and digits and `\\u` escapes are the reader's.) Regenerate with:
  python3 tests/tools/gen-json5-tables.py > /tmp/tables.bf   and replace the file with its content.
"""
import unicodedata

START = {"Lu", "Ll", "Lt", "Lm", "Lo", "Nl"}
PART = START | {"Mn", "Mc", "Nd", "Pc"}


def ranges(categories):
    out = []
    start = None
    for cp in range(0x80, 0x110001):
        ok = cp <= 0x10FFFF and unicodedata.category(chr(cp)) in categories
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def table(name, rs):
    lines = [f"\tinternal static uint32[{len(rs) * 2}] {name} = .("]
    items = [f"0x{a:X}, 0x{b:X}" for a, b in rs]
    row = "\t\t"
    for i, item in enumerate(items):
        piece = item + (", " if i < len(items) - 1 else "")
        if len(row) + len(piece) > 110:
            lines.append(row.rstrip())
            row = "\t\t"
        row += piece
    lines.append(row.rstrip())
    lines.append("\t);")
    return "\n".join(lines)


print(f"""using System;

namespace JsonBeef;

/// JSON5's identifier characters beyond ASCII (ECMAScript 5.1 §7.6): sorted, inclusive code point
/// ranges, as pairs. Generated by tests/tools/gen-json5-tables.py from Unicode {unicodedata.unidata_version}; do not edit.
static class JsonIdentifierTables
{{
	/// UnicodeLetter: Lu, Ll, Lt, Lm, Lo, Nl.
{table("sStart", ranges(START))}

	/// UnicodeLetter and Mn, Mc, Nd, Pc.
{table("sPart", ranges(PART))}

	/// Whether `cp` (≥ 0x80) is in the ranges `table`.
	internal static bool Contains(Span<uint32> table, uint32 cp)
	{{
		// The last range starting at or before cp
		int low = 0;
		int high = table.Length / 2 - 1;
		while (low < high)
		{{
			int mid = (low + high + 1) / 2;
			if (table[mid * 2] <= cp)
				low = mid;
			else
				high = mid - 1;
		}}
		return table[low * 2] <= cp && cp <= table[low * 2 + 1];
	}}
}}""")
