#!/bin/bash
# Builds every comparison harness into bin/ (git-ignored). Run fetch.sh first. C and C++ use -O3
# without -march=native (generic x86-64, like Beef's Release builds; simdjson and sonic-rs still pick
# their SIMD kernels at run time); the C libraries are compiled from the pinned clones straight into
# each harness (no install step, nothing left behind but the binary). Pass harness names to build only
# those: maxrss yyjson cjson json-c jansson yajl simdjson rapidjson nlohmann glaze rust go java cs
# python js perl lua zig beef
set -euo pipefail
C="$(cd "$(dirname "$0")" && pwd)"
D="$C/deps"
B="$C/bin"
L="$C/c/build"
mkdir -p "$B" "$L"

TARGETS=("$@")
want() { [ ${#TARGETS[@]} -eq 0 ] || [[ " ${TARGETS[*]} " == *" $1 "* ]]; }
step() { echo "== $1"; }
CFLAGS="-O3 -DNDEBUG"
CC="${CC:-cc}"
CXX="${CXX:-c++}"

if want maxrss; then
	step "maxrss (peak RSS of a child process, for run.sh)"
	$CC $CFLAGS -std=gnu11 -o "$B/maxrss" "$C/c/maxrss.c"
fi
if want yyjson; then
	step "yyjson (C)"
	$CC $CFLAGS -std=gnu11 -I"$D/yyjson/src" -o "$B/yyjson" "$C/c/yyjson.c" "$D/yyjson/src/yyjson.c"
fi
if want cjson; then
	step "cJSON (C)"
	$CC $CFLAGS -std=gnu11 -I"$D/cJSON" -o "$B/cjson" "$C/c/cjson.c" "$D/cJSON/cJSON.c" -lm
fi
if want json-c; then
	step "json-c (C)"
	# json-c needs its CMake-generated config headers; the build tree is removed afterwards
	cmake -S "$D/json-c" -B "$L/json-c" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF \
		-DBUILD_APPS=OFF -DDISABLE_EXTRA_LIBS=ON -DCMAKE_C_FLAGS_RELEASE="$CFLAGS" \
		-DCMAKE_INSTALL_PREFIX="$L/json-c/install" > /dev/null
	cmake --build "$L/json-c" -j "$(nproc)" --target install > /dev/null
	$CC $CFLAGS -std=gnu11 -I"$L/json-c/install/include" -o "$B/json-c" "$C/c/json-c.c" \
		"$L/json-c/install/lib/libjson-c.a" -lm
	rm -rf "$L/json-c"
fi
if want jansson; then
	step "Jansson (C)"
	cmake -S "$D/jansson" -B "$L/jansson" -DCMAKE_BUILD_TYPE=Release -DJANSSON_BUILD_DOCS=OFF \
		-DJANSSON_WITHOUT_TESTS=ON -DJANSSON_EXAMPLES=OFF -DCMAKE_C_FLAGS_RELEASE="$CFLAGS" \
		-DCMAKE_INSTALL_PREFIX="$L/jansson/install" > /dev/null
	cmake --build "$L/jansson" -j "$(nproc)" --target install > /dev/null
	$CC $CFLAGS -std=gnu11 -I"$L/jansson/install/include" -o "$B/jansson" "$C/c/jansson.c" \
		"$L/jansson/install/lib/libjansson.a"
	rm -rf "$L/jansson"
fi
if want yajl; then
	step "YAJL (C)"
	# yajl_version.h is generated by its CMake build; c/yajl-include holds the one header it needs
	mkdir -p "$L/yajl/yajl"
	cp "$D"/yajl/src/api/*.h "$L/yajl/yajl/"
	sed -e 's/\${YAJL_MAJOR}/2/; s/\${YAJL_MINOR}/1/; s/\${YAJL_MICRO}/0/' "$D/yajl/src/api/yajl_version.h.cmake" \
		> "$L/yajl/yajl/yajl_version.h"
	$CC $CFLAGS -std=gnu11 -I"$L/yajl" -o "$B/yajl" "$C/c/yajl.c" "$D"/yajl/src/yajl*.c
	rm -rf "$L/yajl"
fi
if want simdjson; then
	step "simdjson (C++)"
	$CXX $CFLAGS -std=c++20 -I"$D/simdjson/singleheader" -o "$B/simdjson" "$C/cpp/simdjson.cpp" \
		"$D/simdjson/singleheader/simdjson.cpp"
fi
if want rapidjson; then
	step "RapidJSON (C++)"
	$CXX $CFLAGS -std=c++20 -I"$D/rapidjson/include" -o "$B/rapidjson" "$C/cpp/rapidjson.cpp"
fi
if want nlohmann; then
	step "nlohmann/json (C++)"
	$CXX $CFLAGS -std=c++20 -I"$D/nlohmann-json/single_include" -o "$B/nlohmann" "$C/cpp/nlohmann.cpp"
fi
if want glaze; then
	step "glaze (C++)"
	$CXX $CFLAGS -std=c++23 -I"$D/glaze/include" -o "$B/glaze" "$C/cpp/glaze.cpp"
fi
if want rust; then
	step "rust (serde_json, sonic-rs, simd-json, jiter)"
	# Built from its directory so rustup picks the pinned toolchain in rust-toolchain.toml; no debug
	# info, to keep the target directory small
	(cd "$C/rust" && CARGO_PROFILE_RELEASE_DEBUG=0 cargo build -q --release --locked --target-dir "$C/rust/target")
	cp "$C/rust/target/release/jsonbench" "$B/rust-jsonbench"
	# Again with serde_json's float_roundtrip feature (correctly rounded float parsing, off by default),
	# for the serde_json "float_roundtrip" columns; a Cargo feature applies to the whole binary
	(cd "$C/rust" && CARGO_PROFILE_RELEASE_DEBUG=0 cargo build -q --release --locked --target-dir "$C/rust/target" \
		--features serde-float-roundtrip)
	cp "$C/rust/target/release/jsonbench" "$B/rust-jsonbench-float-roundtrip"
fi
if want go; then
	step "go (encoding/json, encoding/json/v2, sonic, go-json, jsoniter, gjson, jsonparser)"
	(cd "$C/go" && go build -mod=readonly -o "$B/go-jsonbench" .)
fi
if want java; then
	step "java (Jackson, fastjson2, DSL-JSON, Gson)"
	# javac against the jars fetch.sh downloaded (the installed Gradle does not run on JDK 27); bin/java
	# gets the classes, the jars and a launcher script
	JARS=$(printf '%s:' "$D"/jars/*.jar)
	rm -rf "$C/java/build" "$B/java"
	# -proc:full: run DSL-JSON's annotation processor (from its jar) for the @CompiledJson classes; JDK
	# 23+ no longer runs processors found on the class path by default
	javac -nowarn -proc:full -d "$C/java/build/classes" -cp "$JARS" "$C"/java/src/*.java
	mkdir -p "$B/java/bin" "$B/java/lib"
	cp -r "$C/java/build/classes" "$B/java/" && cp "$D"/jars/*.jar "$B/java/lib/"
	printf '#!/bin/sh\nH="$(cd "$(dirname "$0")/.." && pwd)"\nexec java -cp "$H/classes:$H/lib/*" JsonBench "$@"\n' > "$B/java/bin/jsonbench"
	chmod +x "$B/java/bin/jsonbench"
fi
if want cs; then
	step "c# (System.Text.Json, Newtonsoft.Json)"
	dotnet build -v q -nologo -c Release -o "$B/jsonbench-cs" "$C/cs/JsonBench.csproj" > /dev/null
fi
if want python; then
	step "python (json, orjson, msgspec, python-rapidjson, pysimdjson, ijson, pydantic)"
	[ -x "$C/python/.venv/bin/python" ] || python3 -m venv "$C/python/.venv"
	"$C/python/.venv/bin/pip" install -q --disable-pip-version-check -r "$C/python/requirements.txt"
fi
if want js; then
	step "javascript (JSON.parse on Node, Bun and Deno; simdjson_nodejs for Node)"
	# simdjson_nodejs's install script (node-gyp) is blocked by npm's allowScripts, so it runs here
	(cd "$C/js" && npm ci --silent --no-audit --no-fund --ignore-scripts &&
		cd node_modules/simdjson && npx --yes node-gyp@12.4.0 rebuild > /dev/null 2>&1)
fi
if want perl; then
	step "perl (Cpanel::JSON::XS, JSON::XS and its dependencies into perl/local; JSON::PP is the installed Perl's)"
	rm -rf "$L/cpan"
	mkdir -p "$L/cpan"
	# Canary::Stability is JSON::XS's configure-time dependency
	for dist in common-sense-3.75 Types-Serialiser-1.01 Canary-Stability-2013 JSON-XS-4.04 Cpanel-JSON-XS-4.53; do
		tar -xzf "$D/cpan/$dist.tar.gz" -C "$L/cpan"
		(cd "$L/cpan/$dist" && PERL5LIB="$C/perl/local/lib/perl5" PERL_MM_USE_DEFAULT=1 \
			perl Makefile.PL INSTALL_BASE="$C/perl/local" > /dev/null && make -s > /dev/null && make -s install > /dev/null)
	done
	rm -rf "$L/cpan"
fi
if want lua; then
	step "lua (lua-cjson for LuaJIT and for Lua 5.5, and the harness's monotonic clock)"
	mkdir -p "$C/lua/rocks/luajit" "$C/lua/rocks/lua5.5"
	CJSON_SRC=("$D/lua-cjson/lua_cjson.c" "$D/lua-cjson/strbuf.c" "$D/lua-cjson/fpconv.c")
	# /usr/include has the Lua 5.5 headers, /usr/include/luajit-2.1 LuaJIT's (Lua 5.1 API)
	for lua in luajit:/usr/include/luajit-2.1 lua5.5:/usr/include; do
		$CC $CFLAGS -std=gnu11 -fPIC -shared -I"${lua#*:}" -o "$C/lua/rocks/${lua%%:*}/cjson.so" "${CJSON_SRC[@]}"
		$CC $CFLAGS -std=gnu11 -fPIC -shared -I"${lua#*:}" -o "$C/lua/rocks/${lua%%:*}/benchclock.so" "$C/lua/clock.c"
	done
fi
if want zig; then
	step "zig (std.json)"
	ZIG="$D/zig/zig"
	ZC=(--cache-dir "$C/zig/.zig-cache" --global-cache-dir "$C/zig/.zig-cache")
	(cd "$C/zig" && "$ZIG" build-exe -O ReleaseFast -femit-bin="$B/zig-jsonbench" "${ZC[@]}" main.zig)
fi
if want beef; then
	step "beef (JsonBeef, BJSON, EinScott/json, StructuredData)"
	(cd "$C/beef" && beefbuild -config=Release > /dev/null)
	cp "$C/beef/build/Release_Linux64/JsonBeefBench/JsonBeefBench" "$B/beef-jsonbench"
fi
